# -*- mode: ruby -*-
# vi: set ft=ruby :

myboxname = "gabi"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = myboxname
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "./data", "/data"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.name = myboxname
     vb.memory = "512"
     vb.linked_clone = true
   end

  #
  # Provides updated git
  #
  config.vm.provision "git", type: "shell" do |s|
    s.inline = <<-SHELL
      apt-get update
      apt-get install -y apt-transport-https ca-certificates software-properties-common
      apt-get update
      add-apt-repository -y ppa:git-core/ppa
      apt-get install -y git
      git --version
      SHELL
  end

  #
  # Install Hugo binary (no Go interpreter needed)
  #
  config.vm.provision "hugo", type: "shell" do |s|
    s.inline = <<-SHELL
      cd /usr/local/bin
      HUGOVER=0.46
      TARFILE=hugo_${HUGOVER}_Linux-64bit.tar.gz CHKFILE=hugo_${HUGOVER}_checksums.txt
      wget -q --no-check-certificate https://github.com/gohugoio/hugo/releases/download/v${HUGOVER}/$TARFILE -O $TARFILE
      wget -q --no-check-certificate https://github.com/gohugoio/hugo/releases/download/v${HUGOVER}/$CHKFILE -O $CHKFILE 
      sha256sum --ignore-missing -c $CHKFILE || exit 1
      tar xf $TARFILE
      rm -f $TARFILE $CHKFILE
      hugo version
      SHELL
  end
end
